### ISSUE TITLE
Can't navigate to page directly through address bar

### ISSUE THREAD

**Issue by tscully2000** [voldemortensen/svelte-routes#4]
@voldemortensen For whatever reason I can't navigate directly to a page when entering it manually in the address bar. However if I click on a link in the nav bar it goes to the correct page. For context I'm using the default sveltejs template and followed the readme exactly (created a routes.js file and imported that into my App.svelte component). Any help would be appreciated, thanks!

**Comment by voldemortensen** [comment]
You need to rewrite all traffic to /index.html. For apache that would look something like this:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.html [QSA,L]
```

**Comment by tscully2000** [comment]
Ah gotcha. If I'm just running the app on my local dev environment, what comes out of the box with `npx degit sveltejs/template`, how/where would I address the redirecting of traffic?

**Comment by voldemortensen** [comment]
I’m not at a computer right now to verify, but if you edit the start script in package.json to be `sirv -s public` that *should* work.

**Comment by tscully2000** [comment]
@voldemortensen That worked thanks!

**Comment by voldemortensen** [comment]
Awesome! That's for the question, I'm glad it's working for you.
